Move all of include/ into include/SViper/, so that other projects can…
smehringer/SViper pull request #11
Opened 2019-10-16 16:15 UTC by joshuak94

… do #include <SViper/sviper.h>. Also introduce SViper namespace.

2019-10-23 09:37 UTC, smehringer commented
I made some fixes to the files. Can you rebase on current master? The Makefile does not exist anymore. I made this repo into a cmake based project. If you get into troubles I'll help

2019-10-24 11:26 UTC, joshuak94 commented
@smehringer Also done!

2019-10-24 13:40 UTC, smehringer commented
Also again :grin:

2019-11-01 13:11 UTC, joshuak94 commented
@smehringer Can this one and #10 be merged?

2019-11-01 14:38 UTC, smehringer requested changes

2019-11-01 14:38 UTC, smehringer commented on include/SViper/auxiliary.h
> +#include <SViper/basics.h>
Can you change it to `sviper` (no capitals)?

2019-11-04 09:11 UTC, joshuak94 commented
@smehringer Renamed it! I had to remove the "sviper" line from .gitignore, but I think it's okay since the entire build subdirectory is ignored anyways.

2019-11-06 08:38 UTC, joshuak94 commented
@smehringer bump!

2019-11-06 10:05 UTC, smehringer approved these changes

2019-11-06 10:06 UTC, merged