Add threads and output prefix to option constructor.
smehringer/SViper pull request #13
Opened 2019-11-27 12:18 UTC by joshuak94

Currently, other tools using SViper as a library cannot easily change the threads. This allows threads to be set on construction along with specifying the output prefix.

2019-11-27 13:41 UTC, smehringer commented
there is a conflict

2019-11-27 13:49 UTC, joshuak94 commented
@smehringer Fixed!

2019-11-28 07:24 UTC, smehringer requested changes
We need proper CI :see_no_evil: 

Your change now works if the user provides the thread option but if (s)he does not provide the threads they will be set to 0 by default :(
Please change the default on construction (same file above) to `std::thread::hardware_concurrency()`.
If you have some spare time, do you mind finding a small variant/bam file (maybe some extracted sub regio from your file) that we can tests this on?

2019-11-28 08:48 UTC, joshuak94 commented
@smehringer I will do that, but just wanted to point out that this line is then redundant:
https://github.com/smehringer/SViper/blob/72d1e0c3932543adef79765d29c37ff9fca31a8a/include/sviper/sviper.h#L101

2019-11-29 09:49 UTC, smehringer approved these changes

2019-11-29 09:49 UTC, merged